---

- name: Add systemd service unit to lock on sleep
  copy:
    src: 'i3lock-sleep@.service'
    dest: '/etc/systemd/system/i3lock-sleep@.service'
    force: false
    owner: root
    group: root
    mode: 0644

- name: Enable i3lock on sleep for {{ user }}
  systemd:
    name: "i3lock-sleep@{{ user }}"
    enabled: yes


################
# !!!WARNING!!! from here we assume user's home is /home/{{ user }}
###############


- name: Create i3 config directory for {{ user }}
  file:
    path: "/home/{{ user }}/.i3"
    state: directory


- name: Create i3 config files for {{ user }}
  copy:
    src: "{{ item.name }}"
    dest: "/home/{{ user }}/.i3/{{ item.name }}"
    mode: "{{ item.mode }}"
    force: false
  with_items:
    - { name: 'config', mode: '0644' }
    - { name: 'py3status.conf', mode: '0644' }


- name: Put .xinitrc into {{ user }}'s home
  copy:
    src: xinitrc
    dest: "/home/{{ user }}/.xinitrc"
    mode: 0644
    force: false



