---

- getent:
    database: passwd
    key: "{{ user }}"


- set_fact:
    i3_user_home: "{{getent_passwd[user][4]}}"


- name: Create i3 config directory for {{ user }}
  file:
    path: "{{ i3_user_home }}/.i3"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"


- name: Create i3 config files for {{ user }}
  copy:
    force: false
    src: "i3/{{ item.name }}"
    dest: "{{ i3_user_home }}/.i3/{{ item.name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: 'config', mode: '0644' }
    - { name: 'py3status.conf', mode: '0644' }


- name: Put .xinitrc into {{ user }}'s home
  copy:
    force: false
    src: xinitrc
    dest: "{{ i3_user_home }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Install battery low checker script
  copy:
    src: 'battery-low-checker'
    dest: '/usr/bin/battery-low-checker'
    owner: root
    group: root
    mode: 0755

- name: Add systemd service unit to monitor battery level
  copy:
    src: 'battery-low-warning@.service'
    dest: '/etc/systemd/system/battery-low-warning@.service'
    owner: root
    group: root
    mode: 0644


- name: Enable battery low warning service
  systemd:
    name: "battery-low-warning@{{ user }}"
    enabled: yes
    state: started
    daemon_reload: yes
