---

- name: Add systemd service unit to lock on sleep
  copy:
    force: false
    src: 'i3lock-sleep@.service'
    dest: '/etc/systemd/system/i3lock-sleep@.service'
    owner: root
    group: root
    mode: 0644


- name: Enable i3lock on sleep for {{ user }}
  systemd:
    name: "i3lock-sleep@{{ user }}"
    enabled: yes


- getent:
    database: passwd
    key: "{{ user }}"


- set_fact:
    i3_user_home: "{{getent_passwd[user][4]}}"


- name: Create i3 config directory for {{ user }}
  file:
    path: "{{ i3_user_home }}/.i3"
    state: directory


- name: Create i3 config files for {{ user }}
  copy:
    force: false
    src: "{{ item.name }}"
    dest: "{{ i3_user_home }}/.i3/{{ item.name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: 'config', mode: '0644' }
    - { name: 'py3status.conf', mode: '0644' }


- name: Put .xinitrc into {{ user }}'s home
  copy:
    force: false
    src: xinitrc
    dest: "{{ i3_user_home }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
