---

- name: Install Display Server
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
  - xorg
  - xorg-xinit

- name: Install i3 group
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
  - i3-wm
  - i3lock
  - i3status

  # Note: taget_user needs password-less sudo permissions
- name: Install i3cat for custom status items on status bar
  command: yaourt -Sy --noconfirm i3cat-git
  args:
    creates: /usr/bin/i3cat
  become_user: "{{ target_user }}"

  # Note: taget_user needs password-less sudo permissions
- name: Install small utility to read current keyboard layout
  command: yaourt -Sy --noconfirm xkblayout-state
  args:
    creates: /usr/bin/xkblayout-state
  become_user: "{{ target_user }}"

- name: Create i3 config directory for '{{ target_user }}' user
  file: path=~{{target_user}}/.i3
        state=directory
        owner={{ target_user }}
        group={{ target_user }}
        mode=0755

- name: Configure i3 for '{{ target_user }}' user
  copy: src={{ item.name }}
        dest=~{{ target_user }}/.i3/{{ item.name }}
        owner={{ target_user }}
        group={{ target_user }}
        mode={{ item.mode }}
  with_items:
  - { name: 'config', mode: '0644' }
  - { name: 'i3cat.conf', mode: '0644' }
  - { name: 'status.conf', mode: '0644' }
  - { name: 'status-caps-is-on', mode: '0744' }
  - { name: 'status-current-layout', mode: '0744' }

- name: Put .xinitrc in place
  copy: src=xinitrc
        dest=~{{ target_user }}/.xinitrc
        owner={{ target_user }}
        group={{ target_user }}
        mode=0644
