---

- name: Install the X Display Server
  pacman: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - xorg
  - xorg-xinit

- name: Install i3 group
  pacman: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - i3-wm
  - i3lock
  - i3status

- name: Install basic utils for Desktop
  pacman: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - dmenu       # Mod + d => slect app to lunch
  - xclip       # A working clipboard for X
  - alsa-utils  # Contains amixer for sound shortcuts (.i3/config)

- name: Install i3cat for custom status items on status bar
  command: >
    yaourt -Sy --noconfirm i3cat-git
    creates=/usr/bin/i3cat
  become_user: yaourt

- name: Install small utility to read current keyboard layout
  command: >
    yaourt -Sy --noconfirm xkblayout-state
    creates=/usr/bin/xkblayout-state
  become_user: yaourt

- name: Create i3 config directory for '{{ desktop_user }}' user
  file: >
    path=~{{desktop_user}}/.i3
    state=directory
    owner={{ desktop_user }}
    group={{ desktop_user }}
    mode=0755

- name: Configure i3 for '{{ desktop_user }}' user
  copy: >
    src={{ item.name }}
    dest=~{{ desktop_user }}/.i3/{{ item.name }}
    owner={{ desktop_user }}
    group={{ desktop_user }}
    mode={{ item.mode }}
  with_items:
  - { name: 'config', mode: '0644' }
  - { name: 'i3cat.conf', mode: '0644' }
  - { name: 'status.conf', mode: '0644' }
  - { name: 'status-caps-is-on', mode: '0744' }
  - { name: 'status-current-layout', mode: '0744' }

- name: Put .xinitrc into ~{{ desktop_user }}
  copy: >
    src=xinitrc
    dest=~{{ desktop_user }}/.xinitrc
    owner={{ desktop_user }}
    group={{ desktop_user }}
    mode=0644

- name: Start X on tty1 login for '{{ desktop_user }}' user
  blockinfile:
    dest: ~{{ desktop_user }}/.bash_login
    block: |
      if [[ "$(tty)" == '/dev/tty1' ]]; then
        # Start i3-wm if it's not running.
        pidof i3 &> /dev/null || startx
      fi
    backup: yes
