---

- name: Install the X Display Server
  pacman:
    name: [
      'xorg',
      'xorg-xinit' # .xinitrc, startx
    ]
    state: present
    update_cache: yes


- name: Install basic utils for Desktop
  pacman:
    name: [
      'alsa-utils',  # Contains amixer for sound shortcuts (.i3/config)
      'dmenu',       # Mod + d => slect app to lunch
      'gnome-screenshot',
      'redshift',    # Adjusts color temperature for the night
      'terminator',
    ]
    state: present
    update_cache: yes


- name: Install clipit and i3-dmenu
  command: >
    yay -Sy --noconfirm clipit i3-dmenu-desktop
    creates=/usr/bin/clipit
  become_user: yay


- name: Install i3 group
  pacman:
    name: [
      'i3lock',
      'i3-wm',
      'py3status',
    ]
    state: present
    update_cache: yes


- name: Create i3 config directory in /etc/skel
  file:
    path: /etc/skel/.i3
    state: directory


- name: Add default config files to /ets/skel/.i3
  copy:
    src: "{{ item.name }}"
    dest: "/etc/skel/.i3/{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: 'config', mode: '0644' }
  - { name: 'py3status.conf', mode: '0644' }


- name: Put .xinitrc into /etc/skel
  copy:
    src: xinitrc
    dest: /etc/skel/.xinitrc
    mode: 0644


- name: Start X on tty1 login
  blockinfile:
    dest: /etc/skel/.profile
    block: |
      if [[ "$(tty)" == '/dev/tty1' ]]; then
        # Start i3-wm if it's not running.
        pidof i3 &> /dev/null || startx
      fi
    backup: yes
