---

- name: Check if Network Manager is running
  command: pidof NetworkManager
  register: check_nm_running
  failed_when: False
  changed_when: False
  ignore_errors: True

- block:
  - name: Install nm-applet if Network Manager manages network
    pacman: >
      name=network-manager-applet
      state=present

  - name: Run nm-applet with i3-wm if Network Manager manages network
    lineinfile: >
      dest=~{{ desktop_user }}/.i3/config
      line="exec --no-startup-id nm-applet"
  when: check_nm_running.rc == 0
