---

- name: Install the X Display Server
  pacman:
    name: [
        'xorg',
        'xorg-xinit' # .xinitrc, startx
    ]
    state: present
    update_cache: yes


- name: Install i3
  pacman:
    name: [
        'i3lock',
        'i3-wm',

    ]
    state: present
    update_cache: yes


- name: Install Pulseaudio
  pacman:
    name: [
        'pulseaudio',
        'pulseaudio-alsa',
        'pavucontrol', # volume control w/ volume meter
    ]


- name: Install Desktop Utils
  pacman:
    name: [
        'clipmenu',
        'dmenu',       # Mod + d => select app to lunch
        'flameshot',
        'i3status', # py3status needs it
        'ibus',
        'py3status',
        'redshift',
        'terminator',
        'xss-lock',
    ]
    state: present
    update_cache: yes


- name: Install clipit clipboard
  command: >
    yay -Sy --noconfirm clipit
    creates=/usr/bin/clipit
  become_user: yay