# ~/.bash_aliases

# Enable color support of ls and also add handy aliases
if [[ -x /usr/bin/dircolors ]]; then
  if [[ -r ~/.dircolors ]]; then
    eval "$(dircolors -b ~/.dircolors)"
  else
    eval "$(dircolors -b)"
  fi

  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

### Directories ###
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF1'

alias t='tree'

### Searching ###
alias g='grep -sIrEn'
alias qf='find . -name'
alias qfi='find . -iname'

### Git ###
alias b='git branch'
alias c='git commit'
alias d='git diff'
alias s='git status'
