
if type clipit; then
  pgrep clipit &> /dev/null || clipit -d &> /dev/null &
fi

# Set X Background Image with Feh
if [ -x ~/.fehbg ]; then
  ~/.fehbg
fi

# Improve ibus support, some apps require these variables, e.g, Goland
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# fix: gnome-keyring password prompt
dbus-update-activation-environment --systemd \
	 DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

exec ssh-agent -t 1h i3
