---

- name: Install Docker tools
  pacman:
    name: [ 'docker', 'docker-compose' ]
    state: present
    update_cache: yes

- name: Enable and start Docker daemon
  systemd:
    name: docker
    enabled: yes
    state: started
