---

- name: Install Docker
  pacman:
    name: 'docker'
    state: present
    update_cache: yes

- name: Enable and start Docker daemon
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Allow {{ user_name }} to run Docker without sudo
  user:
    name: foobar
    groups: docker
    append: yes

- name: Get users in docker group
  command: "grep ^docker /etc/group"
  register: docker_group_info
  changed_when: False

# Note: I don't use the 'user' module as that would create the user
# if it does not exists instead of failing. Creating is not the responsibility
# of this module.
- name: Add {{ user_name }} to docker group
  command: "usermod --append --groups docker {{ user_name }}"
  when: docker_group_info.stdout is not search(user_name)
