---

# Note: I prefer virtualbox-host-dkms over virtualbox-host-modules-arch.
# It takes some time to compile, but also works with linux-lts or after a
# downgrade of linux.

- name: Install Virtualbox
  pacman:
    name: [
      "linux-headers", # to be able to compile kernel modules
      "virtualbox",
      "virtualbox-guest-iso",
      "virtualbox-host-dkms",
    ]
    state: present
    update_cache: yes


- include_role:
    name: add-user-to-group
  vars:
    user: "{{ user_name }}"
    group: "vboxusers"
