#!/usr/bin/env bash

# TODO: What should be moved to Ansible?

set -x
set -euo pipefail

: "${NEW_HOSTNAME?"Please, provide your desired hostname."}"

# Sanity: Check network connection.
ping -c3 archlinux.org

### Localization settings ###

ln -f -s /usr/share/zoneinfo/Europe/Budapest /etc/localtime
hwclock --systohc --utc

eng_locale='en_US'
sed -i "s/^#${eng_locale}/${eng_locale}/" /etc/locale.gen
hun_locale='hu_HU'
sed -i "s/^#${hun_locale}/${hun_locale}/" /etc/locale.gen

locale-gen

echo "LANG=en_US.UTF-8" > /etc/locale.conf

### Hostname setup ###

echo "${NEW_HOSTNAME}" > /etc/hostname

cat > /etc/hosts <<EOF
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost	${NEW_HOSTNAME}
::1		localhost.localdomain	localhost	${NEW_HOSTNAME}

# End of file
EOF

### Systemd boot

mkinitcpio -p linux

bootctl --path=/boot install

cat > /boot/loader/loader.conf <<EOF
default  arch
editor   0
EOF

# Get PARTUUID for root device into env
eval $(blkid -t PARTLABEL='root' -s PARTUUID -o export)

cat > /boot/loader/entries/arch.conf <<EOF
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options root=PARTUUID=${PARTUUID} rw
EOF


# Make sure wifi-menu command can function properly after reboot, so that I can connect to WiFi easily.
pacman -Sy \
  dialog \
  wpa_supplicant

echo "DO NOT forget to set the root password!!!"
