#!/usr/bin/env bash
#
# !!! DANGER !!!
# If you run this script it will completely erase your data!
# Make sure your understand this script throughly before running it.

set -x
set -euo pipefail


# I know what I'm doing. I'm OK with destroying all my data. (!)
# Note: EXPERIMENTAL script
: "${I_KNOW?'Do you know what you do? (destroying all your data...)'}"

# Sanity: Check network connection.
ping -c3 archlinux.org

timedatectl set-ntp true

root_device='/dev/nvme0n1'
# 0 - boot
# 1 - swap
# 2 - root
# 3 - home
part_ids=('p1' 'p2' 'p3' 'p4')

# Samsung SSD
# Size 1 TB
# Note: I'll only use 50% of the drive and I'll leave 50% if I want to create
# more partitions, e.g., encrypted work drive.
parted_end_of_home="487937MiB" # partition home to be ~300 GB
# parted_end_of_home="-1" # partition home till the end of the drive (max home)
parted "${root_device}" --script -- \
  mklabel gpt \
  mkpart primary fat32 1MiB 513MiB \
  set 1 boot on \
  name 1 boot \
  mkpart primary 513MiB 20993MiB \
  name 2 swap \
  mkpart primary 20993MiB 174593MiB \
  name 3 root  \
  mkpart primary 174593MiB ${parted_end_of_home} \
  name 4 home

mkfs.fat ${root_device}${part_ids[0]}
mkfs.ext4 ${root_device}${part_ids[2]}
mkfs.ext4 ${root_device}${part_ids[3]}

###

mount ${root_device}${part_ids[2]} /mnt
mkdir -p /mnt/{boot,home}
mount ${root_device}${part_ids[0]} /mnt/boot
mount ${root_device}${part_ids[3]} /mnt/home

### Start installation ###

pacstrap /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
