---

- name: Delete .bash_profile (RVM install creates/uses .profile; Ubuntu style)
  file: >
    dest=/etc/skel/.bash_profile
    state=absent

- name: Seed /etc/skel
  copy: >
    src={{ item }}
    dest=/etc/skel/.{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
  - bash_aliases
  - bash_logout
  - bashrc
  - profile

# TODO: review bash_history; peco installation? do we still need the Arch Linux hack?
#- name: Seed /etc/profile.d
#  copy: >
#    src={{ item }}
#    dest=/etc/profile.d/{{ item }}
#    owner=root
#    group=root
#    mode=0644
#  with_items:
#  - bash_history.sh

- name: Insall Bash completion
  pacman: >
    name=bash-completion
    state=present
    update_cache=yes
