---

- name: Insall some packages
  pacman:
    name: [
      'chromium',
      'firefox',
      'smplayer',
      'xf86-video-intel',
    ]
    state: present
    update_cache: yes


- name: Insall file viewer
  pacman:
    name: [
      'thunar',

      'tumbler', # for thumbnails
      'ffmpegthumbnailer', # for video thumbnails
      'poppler-glib', # for PDF thumbnails
    ]
    state: present
    update_cache: yes


- name: Insall some fonts
  pacman:
    name: [
      'adobe-source-code-pro-fonts',
      'adobe-source-sans-pro-fonts',
      'adobe-source-serif-pro-fonts',
      'noto-fonts',
      'noto-fonts-cjk',
      'noto-fonts-emoji',
      'noto-fonts-extra',
      'ttf-dejavu',
    ]
    state: present
    update_cache: yes

