---

- name: Install Intel Video driver
  pacman:
    name: [
      'xf86-video-intel',
    ]
    state: present
    update_cache: yes


- name: Install Web Browsers
  pacman:
    name: [
      'chromium',
      'firefox',
    ]
    state: present
    update_cache: yes


- name: Install Thunar File Viewer
  pacman:
    name: [
      'thunar',
      'tumbler', # for thumbnails
      'ffmpegthumbnailer', # for video thumbnails
      'poppler-glib', # for PDF thumbnails
      'feh', # for image viewing
    ]
    state: present
    update_cache: yes


- name: Install Basic Fonts
  pacman:
    name: [
      'adobe-source-code-pro-fonts',
      'adobe-source-sans-pro-fonts',
      'adobe-source-serif-pro-fonts',
      'noto-fonts',
      'noto-fonts-cjk',
      'noto-fonts-emoji',
      'noto-fonts-extra',
      'ttf-dejavu',
    ]
    state: present
    update_cache: yes


- name: Install Media Player
  pacman:
    name: [
      'smplayer',
    ]
    state: present
    update_cache: yes
