---

# I can never decide when this is sourced. The answer is for login shells.
# Oh, wait... we could use .bash_login, then everything is clear.
- name: Delete confusing .bash_profile
  file: >
    dest=/etc/skel/.bash_profile
    state=absent

- name: Seed /etc/skel
  copy: >
    src={{ item }}
    dest=/etc/skel/.{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
  - bashrc
  - bash_login
  - bash_logout

- name: Create {{ target_user }} user
  user: >
    name={{ target_user }}

- name: Allow passwordless sudo for {{ target_user }} user
  lineinfile: >
    dest=/etc/sudoers
    state=present
    line="{{ target_user }} ALL=(ALL) NOPASSWD: ALL"
    insertafter="root ALL=(ALL) ALL"

- name: Insall my usual packages
  pacman: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - axel
  - gvim
  - htop
  - jdk7-openjdk
  - jdk8-openjdk
  - mc
  - rsync
  - smplayer
  - terminator
  - thunar
  - wget
