---

- name: Insall my usual packages
  pacman: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - axel
  - gvim
  - htop
  - jdk7-openjdk
  - jdk8-openjdk
  - mc
  - mlocate
  - rsync
  - smplayer
  - terminator
  - thunar
  - wget
