---

- name: Insall my usual packages
  pacman:
    name: [
      'axel',
      'gvim',
      'htop',
      'jdk7-openjdk',
      'jdk8-openjdk',
      'mc',
      'mlocate',
      'rsync',
      'smplayer',
      'thunar',
      'wget',
    ]
    state: present
    update_cache: yes
