---

- name: Install Basic Utility Packages
  pacman:
    name: [
      'axel',
      'dmidecode',
      'exfat-utils',
      'gvim', # graphical vim so it can copy to XServer's clipboard
      'htop',
      'jdk7-openjdk',
      'jdk8-openjdk',
      'mlocate',
      'openssh',
      'rsync',
      'tree',
      'unzip',
      'wget',
      'zip',
    ]
    state: present
    update_cache: yes

- name: Install Diagnostic Tools
  pacman:
    name: [
      'intel-gpu-tools', # for intel_gpu_top
      'powertop', # shows CPU energy consumption and avg. freq
      's-tui', # stress testers, show CPU freq and temp
    ]
    state: present
    update_cache: yes
